vpc-name      = "Testing-vpc"
igw-name      = "Testing-igw"
subnet-name   = "Testing-subnet"
rt-name       = "Testing-route-table"
sg-name       = "Testing-sg"
instance-name = "Testing-server"
key-name      = "kw_office_aws"
iam-role      = "Testing-iam-role"